# Generated by Django 6.0 on 2025-12-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sociallinks_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
