# Generated by Django 6.0 on 2025-12-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='category',
            new_name='category_id',
        ),
    ]
