# Generated by Django 6.0 on 2025-12-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_category_blogs_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='category_id',
            new_name='category',
        ),
    ]
